### PR TITLE
Add adapter for Patch Clamp data model

### PR DESCRIPTION
**Pull request by travs**
Now there is a way to PatchClamp models from ChannelWorm's data model to PyOpenWorm's.

In the ChannelWorm directory (not the top-level directory for the repo):
```py
>>> import adapters
>>> import ion_channel.models as C
>>> cw_patch = C.PatchClamp.objects.all()[0]    # get a saved patch-clamp experiment from CW
>>> pca = adapters.PatchClampAdapter(cw_patch)    # create an adapter object with it
>>> pca.get_pow()    # get back the corresponding PyOW model
Experiment(reference=`Evidence(AssertsAllAbout(), year=`None', title=`SALAM', doi=`Salam')', Conditions())
>>> pyow_patch = pca.get_pow()    # assign the PyOW to a variable and use it elsewhere
```

### CODE REVIEW

**Comment by miladjafary** [comment]
@travs Thanks. It's seems interesting. So now we can add add data in channelworm web app model and add it to PyOW as well. :+1: 
could we sync in automatic mode for example by crontab ?

**Comment by VahidGh** [comment]
@travs, Great! What is left is how and when to use this adapter. 
We should talk about this more...

**Comment by VahidGh** [comment]
@travs, It seems like there was a mismatch in naming, would you please add the *adapter.py* to channelworm directory (not ChannelWorm) and remove this folder?

**Comment by miladjafary** [comment]
@travs Please remove adapter.py form "ChannelWorm" and put it in "channelworm" package  . also please duplicated "ChannelWorm" packages.

**Comment by slarson** [comment]
Nice job, @travs!  @VahidGh & @miladjafary if it is just a file move and
directory deletion, you guys know you could just do that with the merged
version yourselves, right?
ᐧ

**Comment by VahidGh** [comment]
@slarson, that was not a big deal :) just a little coincidence and chaos during the name changing issue.
I think now we have a better structure and naming, based on the Django and Python conventions. As it's reliability is important to further developments, I hope this would be the last change in the main structure.

**Pull request merged**
